version: '3.9'

services:
  api1:
    image: leandromandrade/rinha-backend-2023-q3
    container_name: api1
    expose:
      - 8080
    environment:
      PORT: 8080
      MONGODB_URL: 'mongodb://root:root@mongodb:27017/'
      MONGODB_DB: 'rinha_backend'
      NODE_ENV: production
    deploy:
      resources:
        limits:
          cpus: '0.4'
          memory: '960MB'
    depends_on:
      mongodb:
        condition: service_healthy
    networks:
      - support-net
    healthcheck:
      test: curl -o /dev/null -fs --retry 0 --head http://localhost:8080/healthcheck || exit 1
      interval: 10s
      retries: 3
      start_period: 5s
      timeout: 2s

  api2:
    image: leandromandrade/rinha-backend-2023-q3
    container_name: api2
    expose:
      - 8080
    environment:
      PORT: 8080
      MONGODB_URL: 'mongodb://root:root@mongodb:27017/'
      MONGODB_DB: 'rinha_backend'
      NODE_ENV: production
    deploy:
      resources:
        limits:
          cpus: '0.4'
          memory: '960MB'
    depends_on:
      mongodb:
        condition: service_healthy
    networks:
      - support-net
    healthcheck:
      test: curl -o /dev/null -fs --retry 0 --head http://localhost:8080/healthcheck || exit 1
      interval: 10s
      retries: 3
      start_period: 5s
      timeout: 2s

  nginx:
    image: nginx:latest
    volumes:
      - ./ngnix/ngnix.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api1
      - api2
    ports:
      - '9999:9999'
    deploy:
      resources:
        limits:
          cpus: '0.2'
          memory: '128MB'
    networks:
      - support-net

  mongodb:
    image: arm64v8/mongo:5.0
    container_name: mongodb
    hostname: mongodb
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    volumes:
      - ./mongodb:/mongodb
      - ./mongodb/mongo-init.sh:/docker-entrypoint-initdb.d/mongo-init.sh:ro
      - ./data:/data/db
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: '1GB'
    networks:
      - support-net
    healthcheck:
      test: ["CMD", "mongo", "--quiet", "mongodb/rinha_backend", "--eval", "'quit(db.runCommand({ ping: 1 }).ok ? 0 : 2)'" ]
      interval: 10s
      retries: 3
      start_period: 20s
      timeout: 10s


networks:
  support-net:
    driver: bridge
