version: '3'

services:
  mongodb-rinha-backend:
    image: arm64v8/mongo:5.0
    container_name: mongodb-rinha-backend
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    volumes:
      - ./mongodb:/mongodb
      - ./mongodb/mongo-init.sh:/docker-entrypoint-initdb.d/mongo-init.sh:ro
    networks:
      - support-net

  mongodb-express-rinha-backend:
    image: mongo-express
    container_name: mongodb-express-rinha-backend
    restart: always
    ports:
      - '8082:8082'
    depends_on:
      - mongodb-rinha-backend
    environment:
      ME_CONFIG_MONGODB_URL: 'mongodb://root:root@mongodb-rinha-backend:27017'
      ME_CONFIG_MONGODB_AUTH_USERNAME: root
      ME_CONFIG_MONGODB_AUTH_PASSWORD: root
      VCAP_APP_PORT: 8082
    networks:
      - support-net

networks:
  support-net:
    driver: bridge
